service: he-sls

custom:
    esbuild:
        bundle: true
        minify: false
        sourcemap: true
        exclude: ["aws-sdk"]
        target: "node16"
        platform: "node"
        concurrency: 10

provider:
    name: aws
    runtime: nodejs16.x
    region: us-east-1
    stage: ${opt:stage,'dev'}
    apiGateway:
        minimumCompressionSize: 1024
        shouldStartNameWithService: true
    environment:
        STAGE: ${self:provider.stage}
        AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
        NODE_OPTIONS: "--enable-source-maps --stack-trace-limit=1000"
    iam:
        role:
            statements:
                - Effect: Allow
                  Action:
                      - "sqs:*"
                  Resource: "*"

plugins:
    - serverless-esbuild

package:
    individually: true

functions:
    CreateRoom:
        handler: src/infrastructure/lambdas/CreateRoom.handler
        events:
            - http:
                  path: /
                  method: post

    UpdateRoom:
        handler: src/infrastructure/lambdas/UpdateRoom.handler
        events:
            - http:
                  path: /
                  method: put

    DeleteRoom:
        handler: src/infrastructure/lambdas/DeleteRoom.handler
        events:
            - http:
                  path: /{id}
                  method: delete

    FindRoomById:
        handler: src/infrastructure/lambdas/FindRoomById.handler
        events:
            - http:
                  path: /{id}
                  method: get

    FindRoomByFilters:
        handler: src/infrastructure/lambdas/FindRoomByFilters.handler
        events:
            - http:
                  path: /filters
                  method: get
